### ISSUE TITLE
No email field in memberships

### ISSUE THREAD

**Issue by pkissman** [opencycle/opencycle#3]
I just installed opencycle and while trying to add some test data saw this error:

Unknown column 'email' in 'field list' (SQL: update `memberships` set `email` = 1 where `user_id` = 1 and `group_id` in (1))

I was trying to set an email address for a specific group from:

http://<myhost>/groups/<mygroup>/settings

Looks like the create table definition for memberships has no reference to email.

Thanks

Paul Kissman
paul.kissman@state.ma.us

**Comment by threesquared** [comment]
Hi and thanks for your interest! Just FYI Opencycle is still very much in development and so there are likely to be many bugs. Looks like that feature was never actually implemented beyond the frontend so like you said there is no migration or validation etc. I have been busy recently but I will try and find some time to devote to the project soon! However I cant promise anything concrete.

However I am always happy to review PR's if you wanted to contribute? I will also update the README to make the state of the project more obvious. FYI you can see the planned but incomplete feature list on the [roadmap](https://github.com/opencycle/opencycle#feature-roadmap)

**Comment by pkissman** [comment]
Thanks Ben.

I sort of figured that the project wasn’t quite ready for prime time shortly after I submitted the issue below.  I was trying to put up a test post and the whole image upload didn’t function.  Front end was nice.

Unfortunately,  my coding chops are simply not up to the task of contributing.  Otherwise I might offer to try to help. We have one website that runs on CakePHP, which appears not to be too dissimilar to Laravel, but even on Cake,  I just hack around enough to build some very simple functionality and views.  Your project is the first Laravel-based application that I’ve ever been exposed to.

But just for background, let me tell you why I was even trying Opencycle out.

One aspect of my job is to provided support of various kinds (usually grants) to small public libraries in Massachusetts.   Small public libraries often don’t have the budget for new equipment (PC’s, networking equipment, such as routers and switches, etc).  They may be living with very, very old technical infrastructure.  It was suggested to me that we put up an online surplus system, so that larger libraries can post equipment they are ready to let go, and smaller or less affluent libraries can shop around for free equipment that is better than what they have.    That’s the use case .

Thanks again for your quick response.


Paul J. Kissman
Library Information Systems Specialist
Massachusetts Board of Library Commissioners
98 N. Washington St., Suite 401
Boston, MA  02114
paul.kissman@state.ma.us<mailto:paul.kissman@state.ma.us>
mass.gov/mblc or mblc.state.ma.us
Phone: (617)725-1860 . (800)952-7403 (in-state)
Fax: (617)725-0140

**Comment by threesquared** [comment]
That sounds like a perfect use case but yes unfortunately I don't think the project is ready yet. I will keep this issue open to address the initial bug you found and try to find some more time to spend on Opencycle. I would also highly recommend looking more into Laravel though 😄

**Comment by threesquared** [comment]
I am going to close this now as the issue of updating a users group settings has been resolved in the master branch.
