### ISSUE TITLE
Demo site registration - captcha prevents form submission

### ISSUE THREAD

**Issue by pmbranco** [opencycle/opencycle#9]
Demo site registration - captcha prevents form submission
If you can, check the demo website captcha. Right now it is giving an error concerning the site certificate - it prevents user registration and seeing the demo.
Is this finished at the present moment? I can see by the other ticket (May) that it was still under development.

**Comment by threesquared** [comment]
Thanks for pointing that out, I have updated the keys now so registration should be working again.
However yes Opencycle is still very much under development so there are likely to be further issues and missing features.
